# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Focalcrest

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "focalcrest"
BBFILE_PATTERN_focalcrest = "^${LAYERDIR}/"
BBFILE_PRIORITY_focalcrest = "20"

LAYERVERSION_focalcrest = "1"
LAYERDEPENDS_focalcrest = "core rockchip meta-arm openembedded-layer networking-layer"
LAYERSERIES_COMPAT_focalcrest = "wrynose"
