# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Focalcrest

DISTRO = "focalcrest"
DISTRO_NAME = "az0x (Focalcrest AZ0x base distribution)"
DISTRO_VERSION = "6.0"
DISTRO_CODENAME = "wrynose"
SDK_VENDOR = "-fcsdk"
SDK_VERSION = "${DISTRO_VERSION}"
MAINTAINER = "Focalcrest <support@focalcrest.com>"

INIT_MANAGER = "systemd"

DISTRO_FEATURES_OPTED_OUT = " \
    x11 wayland vulkan pulseaudio 3g nfc nfs zeroconf ptest debuginfod \
"

PACKAGE_CLASSES ?= "package_ipk"

LICENSE_CREATE_PACKAGE ?= "1"

require conf/distro/include/focalcrest-versions.inc

BUILD_REPRODUCIBLE_BINARIES ?= "1"

SANITY_TESTED_DISTROS ?= " \
    ubuntu-22.04 \n \
    ubuntu-24.04 \n \
"
